name: Sample Workflow
on: [push]
jobs:
  First-job:
    runs-on: windows-latest
    steps:
      - name: "my first git work flow"
        run: echo "hello-world"
      - name: "multi line script"
        run: |
            dotnet --version