name: Sample Workflow
on: [push]
jobs:
  First-job:
    runs-on: windows-latest
    steps:
      - name: "pulling git repos"
        run: |
            ls -a
            git init
            echo "https://${GITHUB_ACTOR}:${{secrets.GITHHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
            git remote add origin "https://${GITHUB_ACTOR}:${{secrets.GITHHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
            git config --global user.email "Runner@mail.com"
            git config --global user.name "Runner Device"
            git fetch
            git checkout master
            git branch --set-upstream-to=origin/master
            git pull
            ls -a
        shell: bash

      - name: "Building dotnet project"
        run: |
            pwd
            dotnet restore
            dotnet build Time Azure Function.csproj --c "Release"
            dotnet publish Time Azure Function.csproj --c "Release"
      - name: list of files
        run: ls